packages:
  # all packages in subdirectories
  - '@adenta/cli'
  - '@adenta/core'
  - '@adenta/ui'
  - '@adenta/website'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/tests/**'
