packages:
  # all packages in subdirectories
  - 'packages/cli/*'
  - 'packages/cms/*'
  - 'packages/core/*'
  - 'packages/ui/*'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/tests/**'
