export const CollatedErrors: Record<string, Error> = {};

// Dynamic error MDX template function
export function errorContent(id: string) {
  const error = CollatedErrors[id] || id as unknown as Error;
  const message =
    error && typeof error === 'object' && 'message' in error
      ? error.message
      : String(error);
  const stack =
    error && typeof error === 'object' && 'stack' in error
      ? error.stack
      : String(error);
  console.log(stack);
  return `
---
title: Error Message 💡
date: ${new Date().toISOString()}
description: "@adenta/core/mdx-bundler Error."
categories:
- error
meta:
keywords:
    - testing
    - react
    - error
    - dynamic
author:
    - name: "Israel Agyeman-Prempeh"
    - link: "https://github.com/codewreaker"
---
<div
    style={{
    borderRadius: '5px',
    boxShadow: '0 4px 24px rgba(0,0,0,0.08)',
    padding: '2rem 2.5rem',
    margin: '2rem 0',
    border: '1px solid #fcb69f',
    fontFamily: 'Inter, Segoe UI, Arial, sans-serif',
    color: '#2d2d2d',
    position: 'relative',
    }}
>
<div style={{ display: 'flex', alignItems: 'center', gap: '1rem' }}>
<h1 style={{ margin: 0, fontSize: '0.8rem', fontWeight: 700, letterSpacing: '-1px' }}>MDX Bundling Error</h1>
    <span
    style={{
        background: '#ff5e62',
        color: '#fff',
        borderRadius: '999px',
        padding: '0.3em 1em',
        fontSize: '0.7rem',
        fontWeight: 600,
        marginLeft: 'auto',
        boxShadow: '0 2px 8px rgba(255,94,98,0.15)',
    }}
    >
    Total Errors: ${Object.keys(CollatedErrors).length}
    </span>
    </div>
    <p style={{ marginTop: '1.5rem', fontSize: '1.1rem' }}>
    <strong>File:</strong>{' '}
    <code style={{ background: '#fff3cd', color: '#b86b00', padding: '0.1em 0.4em', borderRadius: '0.3em' }}>${id}</code>
    </p>
    <blockquote
    style={{
    background: '#fff3cd',
    color: '#b86b00',
    borderLeft: '4px solid #ff5e62',
    margin: '1.5rem 0',
    padding: '1rem 1.5rem',
    borderRadius: '0.5rem',
    fontSize: '1.1rem',
    }}
    >
    <strong>Message:</strong>
    <br />
    
    <code style={{ fontSize: '1.1rem' }}>${message}</code>
    </blockquote>
    <details style={{ marginTop: '1.5rem' }}>
    <summary style={{ cursor: 'pointer', fontWeight: 600, color: '#ff5e62', fontSize: '1.1rem' }}>
    Show Stack Trace
    </summary>
    <pre
        style={{
        background: '#2d2d2d',
        color: '#fff',
        padding: '1rem',
        borderRadius: '0.5rem',
        marginTop: '1rem',
        overflowX: 'auto',
        fontSize: '0.95rem',
        }}
    >
    {${JSON.stringify(stack)}}
    </pre>
    </details>
</div>

    > ✨ Dynamically generated by **@adenta/core/mdx-bundler**
  `.trim();
}
