# Optimized workflow with matrix strategy for Nx monorepo
# Sequential execution: build -> version -> test (matrix) -> lint (matrix) -> publish
# Uses package-based matrix strategy for parallel testing and linting
# Optimized dependency installation with enhanced caching
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: "@adenta-npm-publish"

on:
  push:
    branches:
      - main    # Triggers when code is pushed to main branch

jobs:
  # Step 1: Build all packages first (single job - dependencies matter)
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC trusted publishing
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Cache pnpm store and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --frozen-lockfile --prefer-offline
        shell: bash

      - name: Print Environment Info
        run: pnpm exec nx report
        shell: bash

      - name: Build packages
        run: pnpm exec nx run-many --target=build --all
        shell: bash

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            packages/*/dist/
          retention-days: 1

  # Step 2: Version packages (single job - modifies repo)
  version:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC trusted publishing
      contents: write  # Required for committing version changes
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Cache pnpm store and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --frozen-lockfile --prefer-offline
        shell: bash

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: .

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Generate Version and Changelog
        run: pnpm exec nx release version --skip-publish
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit Version Changes
        run: |
          git add .
          git diff --staged --quiet || git commit -m "chore(release): update version and changelog"
          git push origin main --follow-tags
        shell: bash

  # Step 3: Matrix strategy for testing - parallel package testing
  test:
    needs: version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Test by package - each package gets its own runner
        package: [cli, core, ui, cms, sandbox]
        # Include test type for packages that have multiple test types
        include:
          - package: cms
            test-type: unit
          - package: cms
            test-type: integration
          - package: cms
            test-type: e2e
          - package: cli
            test-type: unit
          - package: core
            test-type: unit
          - package: ui
            test-type: unit
          - package: sandbox
            test-type: unit
    permissions:
      id-token: write  # Required for OIDC trusted publishing
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Cache pnpm store and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --frozen-lockfile --prefer-offline
        shell: bash

      - name: Run Tests
        run: |
          case "${{ matrix.test-type }}" in
            unit)
              pnpm exec nx test ${{ matrix.package }}
              ;;
            integration)
              pnpm exec nx run ${{ matrix.package }}:test:int
              ;;
            e2e)
              pnpm exec nx run ${{ matrix.package }}:test:e2e
              ;;
            *)
              pnpm exec nx test ${{ matrix.package }}
              ;;
          esac
        shell: bash

  # Step 4: Lint all packages in parallel
  lint:
    needs: version
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [cli, core, ui, cms, sandbox, documentation]
    permissions:
      id-token: write  # Required for OIDC trusted publishing
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Cache pnpm store and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --frozen-lockfile --prefer-offline
        shell: bash

      - name: Run Lint
        run: pnpm exec nx lint ${{ matrix.package }}
        shell: bash

  # Step 5: Publish packages (depends on all tests passing)
  publish:
    needs: [build, version, test, lint]
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for OIDC trusted publishing
      contents: write  # for tagging and releases
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for git history
        
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10
          
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          registry-url: https://registry.npmjs.org/

      - name: Cache pnpm store and dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
            packages/*/node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install dependencies
        run: |
          pnpm config set store-dir ~/.pnpm-store
          pnpm install --frozen-lockfile --prefer-offline
        shell: bash

      - name: Ensure npm 11.5.1 or later for trusted publishing
        run: npm install -g npm@latest
        shell: bash

      - name: Publish packages with Nx Release
        run: pnpm exec nx release publish --verbose
        shell: bash
        env:
          # No NODE_AUTH_TOKEN needed with trusted publishing!
          # OIDC token is automatically generated and used
          NPM_CONFIG_PROVENANCE: true